"""deflaut_unique

Revision ID: 2b9a12d35e08
Revises: beb20ebc1d9a
Create Date: 2023-02-17 20:44:54.603178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9a12d35e08'
down_revision = 'beb20ebc1d9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'links', ['short_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='unique')
    # ### end Alembic commands ###
