"""First_commit

Revision ID: 735ef05c9a26
Revises:
Create Date: 2023-02-18 21:32:39.825626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735ef05c9a26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_key', sa.String(), nullable=True),
    sa.Column('original_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    # ### end Alembic commands ###
